#!/bin/sh
set -e

case "$1" in
    purge)
        rm -f /var/lib/minti/packs/mistral.installed
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
esac

#DEBHELPER#
exit 0
