"""Generator for the MINTI quadrant brand art (the ▚ mark).

Single source of truth for the mark's geometry. Emits:
  assets/logo.svg                 — lockup: quadrant glyph + pixel wordmark + rule + tagline
  assets/wallpaper-3840x2160.svg  — master wallpaper (build VM rasterizes PNGs from it)
  <temp>/minti-brand-preview.png  — pure-Python render for visual review (no rasterizer needed)

Pure stdlib. The wordmark is built from rects on a 5-row pixel grid so the
SVGs have no font dependency for the mark itself (taglines remain <text>,
same as the previous art). Palette per docs/brand.md: cyan glyph, mint
wordmark, grey rule/tagline, #0a0a0a ground. No gradients.

The ▚ quadrant decision is the user's (2026-06-11): two squares of side s,
upper-left + lower-right, touching at exactly one point (the center).
"""
import os
import struct
import zlib

CYAN = "#5fd7ff"
MINT = "#00d787"
GREY = "#8a8a8a"
BG = "#0a0a0a"

CYAN_RGB = (0x5F, 0xD7, 0xFF)
MINT_RGB = (0x00, 0xD7, 0x87)
GREY_RGB = (0x8A, 0x8A, 0x8A)
BG_RGB = (0x0A, 0x0A, 0x0A)

# 5-row pixel font for "MINTI" (X = filled cell)
FONT = {
    "M": ["X...X", "XX.XX", "X.X.X", "X...X", "X...X"],
    "I": ["XXX", ".X.", ".X.", ".X.", "XXX"],
    "N": ["X..X", "XX.X", "X.XX", "X..X", "X..X"],
    "T": ["XXXXX", "..X..", "..X..", "..X..", "..X.."],
}
WORD = "MINTI"
LETTER_GAP = 2  # grid units between letters


def word_runs():
    """Yield (col, row, length) horizontal runs for the whole wordmark."""
    x_off = 0
    for ch in WORD:
        rows = FONT[ch]
        width = len(rows[0])
        for row, bits in enumerate(rows):
            col = 0
            while col < width:
                if bits[col] == "X":
                    start = col
                    while col < width and bits[col] == "X":
                        col += 1
                    yield (x_off + start, row, col - start)
                else:
                    col += 1
        x_off += width + LETTER_GAP


WORD_UNITS = sum(len(FONT[c][0]) for c in WORD) + LETTER_GAP * (len(WORD) - 1)  # 28


def quad_rects(corner_x, corner_y, side):
    """The two quadrant squares whose corners meet at (corner_x, corner_y)."""
    return [
        (corner_x - side, corner_y - side, side, side),  # upper-left
        (corner_x, corner_y, side, side),                # lower-right
    ]


def word_rects(x0, y0, unit):
    return [(x0 + c * unit, y0 + r * unit, l * unit, unit) for c, r, l in word_runs()]


def svg_rect(x, y, w, h, cls):
    return f'  <rect class="{cls}" x="{x}" y="{y}" width="{w}" height="{h}"/>'


def make_logo_svg(path):
    # 320x400 portrait, like the previous lockup. Quadrant corner at (160,120),
    # side 80; wordmark unit 8 -> 224x40 centred; rule; tagline.
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 400" width="320" height="400">',
        "  <!-- MINTI lockup: the ▚ quadrant mark. Generated by scripts/make-brand-art.py -->",
        "  <defs><style>",
        f"    .bg   {{ fill: {BG}; }}",
        f"    .quad {{ fill: {CYAN}; }}",
        f"    .word {{ fill: {MINT}; }}",
        f"    .rule {{ fill: {GREY}; }}",
        f"    .tag  {{ fill: {GREY}; font-family: monospace; font-size: 13px; }}",
        "  </style></defs>",
        svg_rect(0, 0, 320, 400, "bg"),
    ]
    for x, y, w, h in quad_rects(160, 120, 80):
        lines.append(svg_rect(x, y, w, h, "quad"))
    for x, y, w, h in word_rects(48, 240, 8):
        lines.append(svg_rect(x, y, w, h, "word"))
    lines.append(svg_rect(90, 300, 140, 2, "rule"))
    for i, tag in enumerate(["Open agents.", "Open weights.", "Clan-aware."]):
        lines.append(f'  <text class="tag" x="160" y="{330 + i * 22}" text-anchor="middle">{tag}</text>')
    lines.append("</svg>")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{path}")


def make_wallpaper_svg(path):
    # 3840x2160. Same lockup, scaled: corner at (1920,880), side 200;
    # wordmark unit 20 -> 560x100; rule; tagline 38px.
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3840 2160" width="3840" height="2160">',
        "  <!-- MINTI wallpaper: the ▚ quadrant mark on near-black. -->",
        "  <!-- Generated by scripts/make-brand-art.py; build VM rasterizes PNGs from this. -->",
        "  <defs><style>",
        f"    .bg   {{ fill: {BG}; }}",
        f"    .quad {{ fill: {CYAN}; }}",
        f"    .word {{ fill: {MINT}; }}",
        f"    .rule {{ fill: {GREY}; }}",
        f"    .tag  {{ fill: {GREY}; font-family: monospace; font-size: 38px; }}",
        "  </style></defs>",
        svg_rect(0, 0, 3840, 2160, "bg"),
    ]
    for x, y, w, h in quad_rects(1920, 880, 200):
        lines.append(svg_rect(x, y, w, h, "quad"))
    for x, y, w, h in word_rects(1920 - WORD_UNITS * 20 // 2, 1140, 20):
        lines.append(svg_rect(x, y, w, h, "word"))
    lines.append(svg_rect(1920 - 280, 1290, 560, 3, "rule"))
    for i, tag in enumerate(["Open agents.", "Open weights.", "Clan-aware."]):
        lines.append(f'  <text class="tag" x="1920" y="{1360 + i * 56}" text-anchor="middle">{tag}</text>')
    lines.append("</svg>")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{path}")


def make_preview_png(path):
    """Render the lockup (minus taglines — no font rasterizer) at 2x logo scale."""
    w, h = 640, 700
    rects = []
    rects += [(x, y, rw, rh, CYAN_RGB) for x, y, rw, rh in quad_rects(320, 240, 160)]
    rects += [(x, y, rw, rh, MINT_RGB) for x, y, rw, rh in word_rects(96, 480, 16)]
    rects.append((180, 600, 280, 4, GREY_RGB))

    bg_row = bytes(BG_RGB) * w
    rows = []
    for y in range(h):
        row = bytearray(bg_row)
        for rx, ry, rw, rh, color in rects:
            if ry <= y < ry + rh:
                row[rx * 3:(rx + rw) * 3] = bytes(color) * rw
        rows.append(b"\x00" + bytes(row))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
           + chunk(b"IDAT", zlib.compress(b"".join(rows), 9)) + chunk(b"IEND", b""))
    with open(path, "wb") as f:
        f.write(png)
    print(f"{path}: {len(png)} bytes")


if __name__ == "__main__":
    import tempfile
    repo = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    make_logo_svg(os.path.join(repo, "assets", "logo.svg"))
    make_wallpaper_svg(os.path.join(repo, "assets", "wallpaper-3840x2160.svg"))
    make_preview_png(os.path.join(tempfile.gettempdir(), "minti-brand-preview.png"))
