#!/bin/bash
# live-build auto config for MINTI Bookworm amd64 iso-hybrid
set -euo pipefail

lb config noauto \
  --distribution bookworm \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --bootloader syslinux \
  --initsystem systemd \
  --debian-installer false \
  --archive-areas "main contrib non-free non-free-firmware" \
  --apt-recommends false \
  --apt-indices false \
  --memtest none \
  --security false \
  --firmware-chroot false \
  --firmware-binary false \
  --win32-loader false \
  --iso-application "MINTI" \
  --iso-preparer "MINTI Project" \
  --iso-publisher "MINTI Project" \
  --bootappend-live "boot=live components plymouth.enable=0 console=tty0 console=ttyS0,115200" \
  --iso-volume "MINTI-$(date +%Y%m%d)"
